src/Entity/Modules.php
<?php

namespace App\Entity;

use App\Repository\ModulesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ModulesRepository::class)
 */
class Modules
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $Duration;

    /**
     * @ORM\ManyToMany(targetEntity=Formation::class, mappedBy="modules")
     * @ORM\JoinTable(name="formation_modules",
     *      joinColumns={
     *          @ORM\JoinColumn(name="modules_id", referencedColumnName="id")
     *     },
     *     inverseJoinColumns={
     *          @ORM\JoinColumn(name="formation_id", referencedColumnName="id")
     *     }
     * )
     */
    private $formation;

    public function __construct()
    {
        $this->formation = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->Duration;
    }

    public function setDuration(int $Duration): self
    {
        $this->Duration = $Duration;

        return $this;
    }

    /**
     * @return Collection|Formation[]
     */
    public function getFormation(): Collection
    {
        return $this->formation;
    }

    public function addFormation(Formation $formation): self
    {
        if (!$this->formation->contains($formation)) {
            $this->formation[] = $formation;
            $formation->addModule($this);
        }

        return $this;
    }

    public function removeFormation(Formation $formation): self
    {
        $this->formation->removeElement($formation);

        return $this;
    }
}

src/Controller/ModulesController.php
<?php

namespace App\Controller;

use App\Entity\Modules;
use App\Entity\School;
use App\Form\AddModuleType;
use App\Form\AddSchoolType;
use App\Repository\FormationRepository;
use App\Repository\ModulesRepository;
use App\Repository\SchoolRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ModulesController extends AbstractController
{
    /**
     * @Route("/modules", name="modules")
     */
    public function index(ModulesRepository $repo): Response
    {
        $modules = $repo->findAll();
        return $this->render('modules/index.html.twig', [
            'modules' => $modules,
        ]);
    }

    /**
     * @Route("/modules{id}", name="module")
     */
    public function module(ModulesRepository $repo, $id): Response
    {
        $module = $repo->find($id);
        return $this->render('modules/individual_module.html.twig', [
            'module' => $module,
        ]);
    }

    /**
     * @Route("/addModule", name="addModule")
     */
    public function addModule(Request $request, EntityManagerInterface $manager): Response
    {
        $module = new Modules();

        $new_module_form = $this->createForm(AddModuleType::class, $module)->handleRequest($request);

        if ($new_module_form->isSubmitted()){
            $module = $new_module_form->getData();

            $manager->persist($module);

            $manager->flush();

            return $this->redirectToRoute('module', [
                'id' => $module->getId()
            ]);
        }

        return $this->render('modules/add_module.html.twig', [
            'new_module_form' => $new_module_form->createView(),
        ]);
    }

    /**
     * @Route("/updateModule/{id}", name="updateModule")
     */
    public function updateSchool(Request $request, EntityManagerInterface $manager, $id): Response
    {
        $module = $manager->getRepository(Modules::class)->find($id);

        $new_module_form = $this->createForm(AddModuleType::class, $module);

        $new_module_form->handleRequest($request);

        if ($new_module_form->isSubmitted()) {
            $module = $new_module_form->getData();

            $manager->persist($module);

            $manager->flush();

            return $this->redirectToRoute('module', [
                'id' => $id,
            ]);
        }

        return $this->render('modules/add_module.html.twig', [
            'new_module_form' => $new_module_form->createView(),
        ]);
    }

    /**
     * @Route("/deleteModule/{id}", name="deleteModule")
     */
    public function delete($id, EntityManagerInterface $manager, ModulesRepository $repo){
        $module = $repo->find($id);

        $manager->remove($module);
        $manager->flush();

        return $this->redirectToRoute('admin');
    }
}

templates/modules/add_module.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SchoolController!{% endblock %}

{% block body %}
<div class="container">
    <h1>Add a Module</h1>
    {{ form(new_module_form) }}
</div>
{% endblock %}

templates/modules/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ModulesController!{% endblock %}

{% block body %}
    <div class="container">
        <h1>Modules</h1>
        <div class="row">
            {% for module in modules %}
                <div class="col-4">
                    <h2><a href="{{ path('module', {id: module.id}) }}">{{ module.name }}</a></h2>
                    <p>{{ module.description | raw }}</p>
                    <p>Durée : {{ module.duration }} hours</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/modules/individual_module.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ModulesController!{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <h1>{{ module.name }}</h1>
            <p>{{ module.description | raw }}</p>
            <p>Durée : {{ module.duration }} hours</p>
        </div>
        <div class="row">
            <h2>Formations possédant ce module : </h2>
            {% for formation in module.formation %}
                <p><a href="{{ path('formation', {id: formation.id}) }}">{{ formation.name }}</a></p>
            {% endfor %}
        </div>
    </div>
{% endblock %}